language: generic
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:fish-shell/release-2
  - sudo apt-get update
install:
  - sudo apt-get -y install fish
  - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
  - fish -c "fisher add fishtape"
script:
  - fish -c "fishtape test/*_test.fish"
